services:
  - type: web
    name: nestjs-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: 'mongodb+srv://flyinginsect:nm36nyQSSDtnK72e@api-for-frontend.dj2oyzf.mongodb.net/expense-manager?retryWrites=true&w=majority'
